#include <unity.h>

void test_external_clock_priority();
void test_cc_cycles_engine_and_snapshot_updates();
void test_engine_selection_persists_and_updates_scheduler();
void test_granular_source_toggle_via_shift_tone();
void test_mn42_follow_clock_mode();
void test_mn42_debug_meter_toggle();
void test_mn42_transport_latch_behavior();
void test_mn42_usb_channel_normalization();
void test_mn42_hello_resends_ack();
void test_simulator_audio_reports_48k();
void test_preset_round_trip_via_eeprom_store();
void test_init_sim_attaches_default_store();
void test_seed_lock_survives_reseed_and_engine_swap();
void test_global_lock_blocks_reseed_changes();
void test_quantize_control_snaps_pitch_to_scale();
void test_ascii_frame_matches_boot_snapshot();
void test_ascii_renderer_tracks_engine_swaps();
void test_live_input_prime_tags_seeds_as_live();
void test_live_input_prime_respects_all_engine_assignments();
void test_initial_mode_home();
void test_seed_button_transitions_to_seeds();
void test_shift_long_press_returns_home();
void test_alt_long_press_opens_storage_page();
void test_double_tap_moves_to_settings();
void test_chord_shift_alt_seed_enters_perf();
void test_shift_hold_rotate_moves_focus();
void test_scripted_front_panel_walkthrough();
void test_tap_long_press_opens_swing_editor();

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_external_clock_priority);
  RUN_TEST(test_cc_cycles_engine_and_snapshot_updates);
  RUN_TEST(test_engine_selection_persists_and_updates_scheduler);
  RUN_TEST(test_granular_source_toggle_via_shift_tone);
  RUN_TEST(test_mn42_follow_clock_mode);
  RUN_TEST(test_mn42_debug_meter_toggle);
  RUN_TEST(test_mn42_transport_latch_behavior);
  RUN_TEST(test_mn42_usb_channel_normalization);
  RUN_TEST(test_mn42_hello_resends_ack);
  RUN_TEST(test_simulator_audio_reports_48k);
  RUN_TEST(test_preset_round_trip_via_eeprom_store);
  RUN_TEST(test_init_sim_attaches_default_store);
  RUN_TEST(test_seed_lock_survives_reseed_and_engine_swap);
  RUN_TEST(test_global_lock_blocks_reseed_changes);
  RUN_TEST(test_quantize_control_snaps_pitch_to_scale);
  RUN_TEST(test_ascii_frame_matches_boot_snapshot);
  RUN_TEST(test_ascii_renderer_tracks_engine_swaps);
  RUN_TEST(test_live_input_prime_tags_seeds_as_live);
  RUN_TEST(test_live_input_prime_respects_all_engine_assignments);
  RUN_TEST(test_initial_mode_home);
  RUN_TEST(test_seed_button_transitions_to_seeds);
  RUN_TEST(test_shift_long_press_returns_home);
  RUN_TEST(test_alt_long_press_opens_storage_page);
  RUN_TEST(test_double_tap_moves_to_settings);
  RUN_TEST(test_chord_shift_alt_seed_enters_perf);
  RUN_TEST(test_shift_hold_rotate_moves_focus);
  RUN_TEST(test_scripted_front_panel_walkthrough);
  RUN_TEST(test_tap_long_press_opens_swing_editor);
  return UNITY_END();
}
