#pragma once
// @generated by scripts/generate_native_golden_header.py. Edit with caution.

#include <cstddef>

namespace native_golden {

struct FixtureInfo {
    const char* name;
    const char* path;
    const char* expected_hash;
};

constexpr FixtureInfo kAudioFixtures[] = {
    {"drone-intro", "build/fixtures/drone-intro.wav", "f53315eb7db89d33"},
    {"granular-haze", "build/fixtures/granular-haze.wav", "0ba2bd0c8e981ef5"},
    {"layered-euclid-burst", "build/fixtures/layered-euclid-burst.wav", "f58e14d36c461c3a"},
    {"long-random-take", "build/fixtures/long-random-take.wav", "97e954c9e2a909df"},
    {"mixer-console", "build/fixtures/mixer-console.wav", "3ba5f705dc237611"},
    {"modulated-sampler", "build/fixtures/modulated-sampler.wav", "72afd3bf5e65e416"},
    {"quad-bus", "build/fixtures/quad-bus.wav", "8de941a4ffe7446d"},
    {"reseed-A", "build/fixtures/reseed-A.wav", "6bdbf0d855da618f"},
    {"reseed-B", "build/fixtures/reseed-B.wav", "998a54390940abbc"},
    {"reseed-C", "build/fixtures/reseed-C.wav", "1c89c168dc810f77"},
    {"reseed-poly", "build/fixtures/reseed-poly.wav", "c161cef3f5417d05"},
    {"resonator-tail", "build/fixtures/resonator-tail.wav", "e329aa6faffb39f4"},
    {"sampler-grains", "build/fixtures/sampler-grains.wav", "630fbfadca574688"},
    {"surround-bus", "build/fixtures/surround-bus.wav", "ec0a317b727ea022"},
};
constexpr std::size_t kAudioFixtureCount = sizeof(kAudioFixtures) / sizeof(kAudioFixtures[0]);

constexpr FixtureInfo kLogFixtures[] = {
    {"burst-cluster", "build/fixtures/burst-cluster.txt", "082de9ac9a3cb359"},
    {"drone-intro-control", "build/fixtures/drone-intro-control.txt", "d902a9aecc33d807"},
    {"euclid-mask", "build/fixtures/euclid-mask.txt", "2431091b3af7d347"},
    {"granular-haze-control", "build/fixtures/granular-haze-control.txt", "412d5186c87b5cc0"},
    {"layered-euclid-burst-control", "build/fixtures/layered-euclid-burst-control.txt", "5c44c5a0107e630b"},
    {"long-random-take-control", "build/fixtures/long-random-take-control.txt", "8c149dfbb252a955"},
    {"mixer-console-control", "build/fixtures/mixer-console-control.txt", "06483a56b2862b42"},
    {"modulated-sampler-control", "build/fixtures/modulated-sampler-control.txt", "1b950922fea5dd08"},
    {"quad-bus-control", "build/fixtures/quad-bus-control.txt", "c2ca286b9338b4ce"},
    {"reseed-A-control", "build/fixtures/reseed-A-control.txt", "869acd8f643ec981"},
    {"reseed-B-control", "build/fixtures/reseed-B-control.txt", "ceb37aadebabee57"},
    {"reseed-C-control", "build/fixtures/reseed-C-control.txt", "fda53171aa1e1593"},
    {"reseed-log", "build/fixtures/reseed-log.json", "873935e11a5704f3"},
    {"reseed-poly-control", "build/fixtures/reseed-poly-control.txt", "1c9b1f09bf998d2a"},
    {"resonator-tail-control", "build/fixtures/resonator-tail-control.txt", "2712188b6c69ba9a"},
    {"sampler-grains-control", "build/fixtures/sampler-grains-control.txt", "eef0854b3ed98143"},
    {"surround-bus-control", "build/fixtures/surround-bus-control.txt", "440ade6a5be15506"},
};
constexpr std::size_t kLogFixtureCount = sizeof(kLogFixtures) / sizeof(kLogFixtures[0]);

}  // namespace native_golden
