#!/usr/bin/env python3
"""Generate the SeedBox service Mermaid graph from a checked-in manifest."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "docs" / "architecture" / "app_services_map.json"
OUTPUT_PATH = REPO_ROOT / "docs" / "architecture" / "app_services.mmd"


def mermaid_id(raw: str) -> str:
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in raw)


def render() -> str:
    manifest = json.loads(MANIFEST_PATH.read_text())
    groups = manifest["groups"]
    nodes = manifest["nodes"]
    edges = manifest["edges"]

    nodes_by_group: dict[str, list[dict[str, str]]] = {group["id"]: [] for group in groups}
    labels: dict[str, str] = {}
    for node in nodes:
        nodes_by_group[node["group"]].append(node)
        labels[node["id"]] = node["label"]

    lines = [
        "%% This file is generated by scripts/generate_app_service_map.py.",
        "%% Edit docs/architecture/app_services_map.json, then regenerate.",
        "flowchart TD",
    ]

    for group in groups:
        lines.append(f'  subgraph {mermaid_id(group["id"])}["{group["label"]}"]')
        for node in nodes_by_group[group["id"]]:
            lines.append(f'    {mermaid_id(node["id"])}["{node["label"]}"]')
        lines.append("  end")

    for edge in edges:
        source = mermaid_id(edge["from"])
        target = mermaid_id(edge["to"])
        label = edge.get("label")
        if label:
            lines.append(f"  {source} -->|{label}| {target}")
        else:
            lines.append(f"  {source} --> {target}")

    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(render())
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
